// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pwned_passwords.proto

package pwnedpasswords

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	HashPrefix           string   `protobuf:"bytes,1,opt,name=hashPrefix" json:"hashPrefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwned_passwords_39c528713f4b8dfb, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetHashPrefix() string {
	if m != nil {
		return m.HashPrefix
	}
	return ""
}

type PasswordHash struct {
	HashSuffix           []byte   `protobuf:"bytes,1,opt,name=hashSuffix,proto3" json:"hashSuffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordHash) Reset()         { *m = PasswordHash{} }
func (m *PasswordHash) String() string { return proto.CompactTextString(m) }
func (*PasswordHash) ProtoMessage()    {}
func (*PasswordHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_pwned_passwords_39c528713f4b8dfb, []int{1}
}
func (m *PasswordHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordHash.Unmarshal(m, b)
}
func (m *PasswordHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordHash.Marshal(b, m, deterministic)
}
func (dst *PasswordHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordHash.Merge(dst, src)
}
func (m *PasswordHash) XXX_Size() int {
	return xxx_messageInfo_PasswordHash.Size(m)
}
func (m *PasswordHash) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordHash.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordHash proto.InternalMessageInfo

func (m *PasswordHash) GetHashSuffix() []byte {
	if m != nil {
		return m.HashSuffix
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "pwnedpasswords.ListRequest")
	proto.RegisterType((*PasswordHash)(nil), "pwnedpasswords.PasswordHash")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PwnedPasswordsClient is the client API for PwnedPasswords service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PwnedPasswordsClient interface {
	ListHashesForPrefix(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (PwnedPasswords_ListHashesForPrefixClient, error)
}

type pwnedPasswordsClient struct {
	cc *grpc.ClientConn
}

func NewPwnedPasswordsClient(cc *grpc.ClientConn) PwnedPasswordsClient {
	return &pwnedPasswordsClient{cc}
}

func (c *pwnedPasswordsClient) ListHashesForPrefix(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (PwnedPasswords_ListHashesForPrefixClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PwnedPasswords_serviceDesc.Streams[0], "/pwnedpasswords.PwnedPasswords/ListHashesForPrefix", opts...)
	if err != nil {
		return nil, err
	}
	x := &pwnedPasswordsListHashesForPrefixClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PwnedPasswords_ListHashesForPrefixClient interface {
	Recv() (*PasswordHash, error)
	grpc.ClientStream
}

type pwnedPasswordsListHashesForPrefixClient struct {
	grpc.ClientStream
}

func (x *pwnedPasswordsListHashesForPrefixClient) Recv() (*PasswordHash, error) {
	m := new(PasswordHash)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PwnedPasswordsServer is the server API for PwnedPasswords service.
type PwnedPasswordsServer interface {
	ListHashesForPrefix(*ListRequest, PwnedPasswords_ListHashesForPrefixServer) error
}

func RegisterPwnedPasswordsServer(s *grpc.Server, srv PwnedPasswordsServer) {
	s.RegisterService(&_PwnedPasswords_serviceDesc, srv)
}

func _PwnedPasswords_ListHashesForPrefix_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PwnedPasswordsServer).ListHashesForPrefix(m, &pwnedPasswordsListHashesForPrefixServer{stream})
}

type PwnedPasswords_ListHashesForPrefixServer interface {
	Send(*PasswordHash) error
	grpc.ServerStream
}

type pwnedPasswordsListHashesForPrefixServer struct {
	grpc.ServerStream
}

func (x *pwnedPasswordsListHashesForPrefixServer) Send(m *PasswordHash) error {
	return x.ServerStream.SendMsg(m)
}

var _PwnedPasswords_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pwnedpasswords.PwnedPasswords",
	HandlerType: (*PwnedPasswordsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListHashesForPrefix",
			Handler:       _PwnedPasswords_ListHashesForPrefix_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pwned_passwords.proto",
}

func init() {
	proto.RegisterFile("pwned_passwords.proto", fileDescriptor_pwned_passwords_39c528713f4b8dfb)
}

var fileDescriptor_pwned_passwords_39c528713f4b8dfb = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xcf, 0x4b,
	0x4d, 0x89, 0x2f, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x03, 0x0b, 0xc3, 0x45, 0x95, 0x74, 0xb9, 0xb8, 0x7d, 0x32, 0x8b, 0x4b, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xe4, 0xb8, 0xb8, 0x32, 0x12, 0x8b, 0x33, 0x02, 0x8a,
	0x52, 0xd3, 0x32, 0x2b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x94, 0xf4, 0xb8,
	0x78, 0x02, 0xa0, 0x7a, 0x3d, 0x12, 0x8b, 0x33, 0x60, 0xea, 0x83, 0x4b, 0xd3, 0x60, 0xea, 0x79,
	0x82, 0x90, 0x44, 0x8c, 0xd2, 0xb8, 0xf8, 0x02, 0x40, 0x16, 0xc2, 0x34, 0x15, 0x0b, 0x85, 0x70,
	0x09, 0x83, 0x2c, 0x04, 0xe9, 0x4e, 0x2d, 0x76, 0xcb, 0x2f, 0x82, 0x18, 0x2c, 0x24, 0xad, 0x87,
	0xea, 0x30, 0x3d, 0x24, 0x57, 0x49, 0xc9, 0xa0, 0x4b, 0x22, 0xbb, 0x41, 0x89, 0xc1, 0x80, 0x31,
	0x89, 0x0d, 0xec, 0x3b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xe4, 0xb1, 0x7d, 0xf6,
	0x00, 0x00, 0x00,
}
