// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: pwned_passwords.proto

/*
Package pwnedpasswords is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pwnedpasswords

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_PwnedPasswords_ListHashesForPrefix_0(ctx context.Context, marshaler runtime.Marshaler, client PwnedPasswordsClient, req *http.Request, pathParams map[string]string) (PwnedPasswords_ListHashesForPrefixClient, runtime.ServerMetadata, error) {
	var protoReq ListRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["hashPrefix"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "hashPrefix")
	}

	protoReq.HashPrefix, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "hashPrefix", err)
	}

	stream, err := client.ListHashesForPrefix(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterPwnedPasswordsHandlerFromEndpoint is same as RegisterPwnedPasswordsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterPwnedPasswordsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterPwnedPasswordsHandler(ctx, mux, conn)
}

// RegisterPwnedPasswordsHandler registers the http handlers for service PwnedPasswords to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterPwnedPasswordsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterPwnedPasswordsHandlerClient(ctx, mux, NewPwnedPasswordsClient(conn))
}

// RegisterPwnedPasswordsHandlerClient registers the http handlers for service PwnedPasswords
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "PwnedPasswordsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "PwnedPasswordsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "PwnedPasswordsClient" to call the correct interceptors.
func RegisterPwnedPasswordsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client PwnedPasswordsClient) error {

	mux.Handle("GET", pattern_PwnedPasswords_ListHashesForPrefix_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_PwnedPasswords_ListHashesForPrefix_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_PwnedPasswords_ListHashesForPrefix_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_PwnedPasswords_ListHashesForPrefix_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1", "hashes", "hashPrefix", "list"}, ""))
)

var (
	forward_PwnedPasswords_ListHashesForPrefix_0 = runtime.ForwardResponseStream
)
